todopro/todoapp/urls.py
from django.urls import path
from . import  views
app_name='todoapp'
urlpatterns = [
    path('',views.index,name='index'),
    # path('details/',views.details,name='details'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvlist/',views.tasklist.as_view(),name='cbvlist'),
    path('cbvdetails/<int:pk>',views.taskdetail.as_view(),name='cbvdetails'),
    path('cbvupdate/<int:pk>',views.taskupdate.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>', views.taskdelete.as_view(), name='cbvdelete'),

    ]

todopro/todopro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todopro/todoapp/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    name=models.CharField(max_length=250)
    prio=models.IntegerField()
    date=models.DateField()


    def __str__(self):
        return self.name

todopro/todoapp/forms.py
from django import forms
from .models import task

class taskeform(forms.ModelForm):
    class Meta:
        model=task
        fields=['name','prio','date']

todopro/todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import task
from .forms import taskeform
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from  django.views.generic.edit import UpdateView,DeleteView

# Create your views here.

class tasklist(ListView):
    model = task
    template_name = 'index.html'
    context_object_name = 'tas'

class taskdetail(DetailView):
    model = task
    template_name = 'details.html'
    context_object_name = 'tas'

class taskupdate(UpdateView):
    model = task
    template_name = 'update.html'
    context_object_name = 'task'
    fields=('name','prio','date')

    def get_success_url(self):
        return reverse_lazy('cbvdetails',kwargs={'pk': self.object.id})


class taskdelete(DeleteView):
    model = task
    template_name = 'delete.html'
    success_url = reverse_lazy('cbvlist')











def index(request):
    tas = task.objects.all()
    if request.method == "POST":
        name = request.POST.get('name','')
        prio = request.POST.get('prio','')
        date = request.POST.get('date', '')

        tasks=task(name=name, prio=prio,date=date)
        tasks.save()
    return render(request,'index.html',{'task':tas})



def delete(request,id):
    if request.method=='POST':
        tas=task.objects.get(id=id)
        tas.delete()
        return redirect('/')
    return render(request,'delete.html')



def update(request,id):
    tas=task.objects.get(id=id)
    form=taskeform(request.POST or None, request.FILES,instance=tas)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'update.html', {'form':form,'tas':tas})

#
# def details(request):
#     tas=task.objects.all()
#     return  render(request,"details.html",{'task':tas})

todopro/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TO-DO task | home</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous"><!--    <link rel="stylesheet" href="{%static 'stylesheet.css' %}" >-->
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}">
</head>

<body >
<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
        <div class="banner">
        <div class="banner-body">
            <p><b>To-Do</b></p>

        </div>


    </div>
</div>
    </div>
    </div>
{% block body %}
{% endblock %}

</body>
</html>

todopro/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="shaa" style="padding:12px;background-color:black">
        <form method="post" >
    {% csrf_token %}

    <h2>Do you want to <b>delete</b> this task from list ?</h2><br>

    <button type="submit" class="btn btn-danger">Yes</button>
        <a href="{% url 'todoapp:index' %}" class="btn btn-primary">No</a>

</form>

    </div>

</div>

{% endblock %}

todopro/templates/details.html
{% extends 'base.html' %}
{% block body %}



        <div class="shadow card" style="width: 30rem;border-radius: 16px; ">
            <div class="shaa">
            <div class="card-body" style="background-color: #2C3E50  ">
                <h4 class="card-title">Priority :{{tas.prio}}</h4>
                <h3>Date : {{tas.date}}</h3>
                <h2>{{tas.name}}</h2>
                <a  href="{% url 'todoapp:update' tas.id %}" class="btn btn-success">Update</a>
                <a  href="{% url 'todoapp:delete' tas.id %}" class="btn btn-danger">Done</a>

            </div>
</div>
        </div><br>




{% endblock %}

todopro/templates/index.html
{% extends 'base.html' %}
{% block body %}
<!--current task-->






<div class="container">
<br><br>
<br>
<h1>Current Tasks</h1>

<div class="row">
    <div class="col-md-6">
        {% for i in task %}

        <div class="shadow card" style="width: 30rem;border-radius: 16px; ">
            <div class="shaa">
            <div class="card-body" style="background-color: #2C3E50  ">
                <h4 class="card-title">Priority :{{i.prio}}</h4>
                <h3>Id : {{i.id}}</h3>
                <h3>Date : {{i.date}}</h3>
                <h2>{{i.name}}</h2>
                <a  href="{% url 'todoapp:update' i.id %}" class="btn btn-success">Update</a>
                <a  href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>

            </div>
</div>
        </div><br>

         {% endfor %}
    </div>








<!--add task-->




  <div class="col-md-6">

<div class="boxing">

     <h3 >Add Your Task</h3><br>


        <form method="post"  >
            <div class="mp-3 shadow">
            {% csrf_token %}
<!--                <label class="form-control">Name of task   :</label>-->
            <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Name of task  ">
            </div>
<!--             <label class="form-control">Priority      :</label>-->
            <div class="form-group">
                <input type="number" name="prio" class="form-control" placeholder="Priority">
            </div>
                <div class="form-group">
                <input type="date" name="date" class="form-control" placeholder="Date">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Add Task</button>
                <button type="reset" class="btn btn-danger">Cancel</button>
            </div>
        </form>
  </div> </div>

    </div>    </div>
</div>






{% endblock %}

todopro/templates/update.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="shaa" style="padding:12px;background-color:black">

        <h2>Update the details</h2><hr>
<form method="post">
  <h4>
    {% csrf_token %}
    {{form.as_p}}<br></h4>

  <button type="submit" class="btn btn-warning">Update </button>
  <a href="{% url 'todoapp:index' %}" class="btn btn-primary">Cancel</a>

</form>
    </div></div>

{% endblock %}